FROM ubuntu:15.10
MAINTAINER guodong <gd@tongjo.com>
RUN apt-get update
RUN apt-get install -y wget
RUN cd /root && wget http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2%20x64.tar.bz2 && tar -jxvf Sublime\ Text\ 2.0.2\ x64.tar.bz2
CMD /root/Sublime\ Text\ 2/sublime_text